export const ACTION_START_SEARCH = "ACTION_START_SEARCH";
export const ACTION_CLEAR_SEARCH_RESULT = "ACTION_CLEAR_SEARCH_RESULT";

export const ACTION_CLEAR_KEYWORD = "ACTION_CLEAR_KEYWORD";

export const ACTION_START_FETCHING_RANDOM = "ACTION_START_FETCHING_RANDOM";
export const ACTION_PUT_RESULT_RANDOM_LIST = "ACTION_PUT_RESULT_RANDOM_LIST";
export const ACTION_PUSH_RESULT_RANDOM_LIST = "ACTION_PUSH_RESULT_RANDOM_LIST";
export const ACTION_FINISH_FETCHING_RANDOM = "ACTION_FINISH_FETCHING_RANDOM";
export const ACTION_CLEAR_RANDOM_RESULT = "ACTION_CLEAR_RANDOM_RESULT";
export const ACTION_UPDATE_RANDOM_OFFSET = "ACTION_UPDATE_RANDOM_OFFSET";

export const ACTION_PUT_RESULT_RECIPES_LIST = "ACTION_PUT_RESULT_RECIPES_LIST";
export const ACTION_PUSH_RESULT_RECIPES_LIST = "ACTION_PUSH_RESULT_RECIPES_LIST";

export const ACTION_FINISH_SEARCH = "ACTION_FINISH_SEARCH";
export const ACTION_UPDATE_OFFSET = "ACTION_UPDATE_OFFSET";

export const ACTION_START_SEARCH_RECIPES_BY_CUISINE = 'ACTION_START_SEARCH_RECIPES_BY_CUISINE';
export const ACTION_FINISH_SEARCH_RECIPES_BY_CUISINE = 'ACTION_FINISH_SEARCH_RECIPES_BY_CUISINE';
export const ACTION_PUSH_RESULT_RECIPES_BY_CUISINE = 'ACTION_PUSH_RESULT_RECIPES_BY_CUISINE';
export const ACTION_CLEAR_RESULT_RECIPES_BY_CUISINE = 'ACTION_CLEAR_RESULT_RECIPES_BY_CUISINE';

export const ACTION_START_GET_RECIPES_BY_CATEGORY = 'ACTION_START_GET_RECIPES_BY_CATEGORY';
export const ACTION_PUSH_RECIPES_BY_CATEGORY = 'ACTION_PUSH_RECIPES_BY_CATEGORY';
export const ACTION_CLEAR_RECIPES_BY_CATEGORY = 'ACTION_CLEAR_RECIPES_BY_CATEGORY';
export const ACTION_FINISH_RECIPES_BY_CATEGORY = 'ACTION_FINISH_RECIPES_BY_CATEGORY';

export const ACTION_UPDATE_RECIPE = 'ACTION_UPDATE_RECIPE';

export const ACTION_CATEGORY_FETCH_START = "ACTION_CATEGORY_FETCH_START";
export const ACTION_CATEGORY_FETCH_SUCCESS = "ACTION_CATEGORY_FETCH_SUCCESS";
export const ACTION_CATEGORY_FETCH_ERROR = "ACTION_CATEGORY_FETCH_ERROR";

export const ACTION_CUISINE_FETCH_START = "ACTION_CUISINE_FETCH_START";
export const ACTION_CUISINE_FETCH_SUCCESS = "ACTION_CUISINE_FETCH_SUCCESS";
export const ACTION_CUISINE_FETCH_ERROR = "ACTION_CUISINE_FETCH_ERROR";

export const ACTION_IMAGE_CACHING_ADD_QUEUE = "ACTION_IMAGE_CACHING_ADD_QUEUE";
export const ACTION_IMAGE_CACHING_DOWNLOAD_START = "ACTION_IMAGE_CACHING_DOWNLOAD_START";
export const ACTION_IMAGE_CACHING_DOWNLOAD_SUCCESS = "ACTION_IMAGE_CACHING_DOWNLOAD_SUCCESS";
export const ACTION_IMAGE_CACHING_DOWNLOAD_FAILED = "ACTION_IMAGE_CACHING_DOWNLOAD_FAILED";

export const ACTION_SET_SELECTED_LANGUAGE = "ACTION_SET_SELECTED_LANGUAGE";
